name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r src/python-client/requirements.txt pytest moto boto3

      - name: Run tests
        run: |
          cd src/python-client
          pytest --maxfail=1 --disable-warnings -q

  benchmark:
    needs: test
    runs-on: ubuntu-latest
    # only run if AWS credentials are set in Secrets
    if: secrets.AWS_ACCESS_KEY_ID != '' && secrets.AWS_SECRET_ACCESS_KEY != ''
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install benchmark dependency
        run: pip install boto3

      - name: Run benchmark
        run: python benchmark/benchmark.py
